# Generated by Django 5.0.4 on 2024-08-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTicket',
            fields=[
                ('id_ticket', models.CharField(primary_key=True, max_length=30)),
                ('username_create_ticket', models.CharField(max_length=30)),
                ('date_create_ticket', models.DateTimeField()),
            ],
        ),
    ]
