# Generated by Django 5.0.4 on 2024-08-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataClosedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ticket', models.CharField()),
                ('username_create_ticket', models.CharField(null=True)),
                ('date_create_ticket', models.DateTimeField(null=True)),
                ('accept_staff_name', models.CharField(null=True)),
                ('date_accept_ticket', models.DateTimeField(null=True)),
                ('date_closed_ticket', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTicket',
            fields=[
                ('id_ticket', models.CharField(primary_key=True, serialize=False)),
                ('username_create_ticket', models.CharField(null=True)),
                ('date_create_ticket', models.DateTimeField(null=True)),
                ('accept_staff_name', models.CharField(null=True)),
                ('date_accept_ticket', models.DateTimeField(null=True)),
            ],
        ),
    ]
